apiVersion: v1
kind: Service
metadata:
  labels:
    app: angular
  name: angular
  namespace: angular
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: angular
  type: NodePort