apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: angular
  name: angular
  namespace: angular
spec:
  replicas: 2
  selector:
    matchLabels:
      app: angular
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
      - image: mohamedaminbenhamissa/devops-test:latest
        imagePullPolicy: Always
        name: angular
      restartPolicy: Always
